stages:
  - setup
  - test

default:
  before_script:


setup:
  stage: setup
  script:
    - cd client
    - echo n | npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

variables:
  GIT_DEPTH: 0

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test
