stages:
  - setup
  - test
  - deploy

default:
  before_script:


setup:
  stage: setup
  script:
    - cd client
    - echo n | npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

variables:
  GIT_DEPTH: 0

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test

jasmine:
  stage: test
  script:
    - cd client
    - ng test --browsers ChromeHeadlessNoSandbox --watch=false


deploy-test-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - ./gradlew bootJar
    # Move artifact to clean directory
    - rm -rf ~/test-server/ || true
    - mkdir -p ~/test-server/
    - cp -r ./build/libs ~/test-server
    # Update bash script and restart service
    - rm -f ~/runTestServer.sh || true
    - cp ../deployment-scripts/runTestServer.sh ~/runTestServer.sh
    # Copy new service file and restart service
    - cp ../deployment-scripts/testServer.service /etc/systemd/system/
    - sudo systemctl enable testServer.service|| true   # Is the || true nessesary?
    - sudo systemctl restart testServer 
#  only:
#    refs:
#      - development


