stages:
  - setup
  - test
  - deploy

default:
  before_script:


setup:
  stage: setup
  script:
    - cd client
    - echo n | npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

variables:
  GIT_DEPTH: 0

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test

jasmine:
  stage: test
  script:
    - cd client
    - ng test --browsers ChromeHeadlessNoSandbox --watch=false


deploy-test-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - rm -f ./build/libs/*.war || true
    - ./gradlew bootWar -PspringProfile=local
    # Move artifact to volume shared by tomcat
    - rm -f /home/gitlab-runner/test-server/*.war || true
    - cp ./build/libs/*.war /home/gitlab-runner/test-server
#  only:
#    refs:
#      - development



deploy-test-client:
  stage: deploy
  script:
    # Create artifact
    - cd client
    - ng --prod --aot build
    # Move artifact to volume shared by apache
    - rm -rf /home/gitlab-runner/test-client/* || true
    - cp -r ./dist/client/* /home/gitlab-runner/test-client/
#  only:
#    refs:
#      - development
