version: '2.4'
services:
    
    prodMySQL:
        image: 'mysql:8.0.22'
        container_name: prod-mysql
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - 'prod-mysql-data:/var/lib/mysql'
        environment:
                MYSQL_DATABASE: capacitor_prod
        env_file:
            - mysql.env


    prodDatabaseBackup:
        image: 'capacitor-mysql-backup:latest-prod'
        build:
            context: ./dockerfiles/custom-mysql-backup-container/
            args:
                 - FILENAME_SCRIPT=ch-name_prod.sh

        container_name: prod-mysql-backup
        restart: always
        environment:
            - DB_SERVER=172.17.0.1
            - DB_USER=root
            - DB_PORT=3306
            # Once a day 60*24=1440
            - DB_DUMP_FREQ=1440
            # Start each backup at 9:05 PM NZST
            - DB_DUMP_BEGIN=0805
            - DB_DUMP_SAFECHARS
            - 'MYSQLDUMP_OPTS=--ignore-table=mysql.innodb_index_stats --ignore-table=mysql.innodb_table_stats'
        env_file:
            - mysql-backup.env
        depends_on:
            - prodMySQL
    

    testMySQL:
        image: 'mysql:8.0.22'
        container_name: test-mysql
        restart: always
        ports:
            - '3307:3306'
        volumes:
            - 'test-mysql-data:/var/lib/mysql'
        environment:
                MYSQL_DATABASE: capacitor_test
        env_file:
            - mysql.env
    

    testDatabaseBackup:
        image: 'capacitor-mysql-backup:latest-test'
        build:
            context: ./dockerfiles/custom-mysql-backup-container/
            args:
                 - FILENAME_SCRIPT=ch-name_test.sh

        container_name: test-mysql-backup
        restart: always
        environment:
            - DB_SERVER=172.17.0.1
            - DB_USER=root
            - DB_PORT=3307
            # Once a day 60*24=1440
            - DB_DUMP_FREQ=1440
            # Start each backup at 9:35 PM NZST
            - DB_DUMP_BEGIN=0835
            - DB_DUMP_SAFECHARS
            - 'MYSQLDUMP_OPTS=--ignore-table=mysql.innodb_index_stats --ignore-table=mysql.innodb_table_stats'
        env_file:
            - mysql-backup.env
        depends_on:
            - testMySQL


    phpmyadmin:
        container_name: phpmyadmin
        image: 'capacitor-phpmyadmin:latest'
        build: ./dockerfiles/custom-phpmyadmin-container/
        environment:
            # The address 172.17.0.1 is localhost for docker
            - PMA_HOSTS=172.17.0.1,172.17.0.1
            - PMA_PORTS=3306,3307
            - PMA_VERBOSES=prod,test
        restart: always
        ports:
            - '8081:443'
        volumes:
            - '/etc/apache2/ssl:/certs:ro'
        hostname: 'capacitor-archive.com'


    capacitor-gitlab-runner:
        container_name: gitlab-runner
        image: 'capacitor-gitlab-runner:latest'
        build: ./dockerfiles/custom-gitlab-runner-container/
        restart: always
        cpus: 1.2
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'gitlab-runner-config:/etc/gitlab-runner'
            - 'test-client-build:/home/gitlab-runner/test-client/'
            - 'test-server-build:/home/gitlab-runner/test-server/'
            - 'prod-client-build:/home/gitlab-runner/prod-client/'
            - 'prod-server-build:/home/gitlab-runner/prod-server/'


    ddclient:
        image: 'capacitor-ddclient:latest'
        build: 
            context: ./dockerfiles/custom-ddclient-container/
        container_name: ddclient
        environment:
            - PUID=1000
            - PGID=1000
            - 'TZ=New Zealand/Wellington'
        env_file:
            - ddclient.env
        restart: unless-stopped



#########################
# Deployment Environments
#########################


    testClient:
        container_name: test-client
        image: 'httpd-custom-config:latest'
        build: ./dockerfiles/custom-httpd-container/
        restart: always
        ports:
            - '35506:80'
        volumes:
            - 'test-client-build:/usr/local/apache2/htdocs/'


    testServer:
        container_name: test-server
        image: 'tomcat:9.0'
        restart: always
        ports:
            - '35505:8080'
        depends_on:
            - testMySQL
        environment:
            - JAVA_OPTS=-Dspring.profiles.active=dev
        volumes:
            - 'test-server-build:/usr/local/tomcat/webapps/'


    prodClient:
        container_name: prod-client
        image: 'httpd-custom-config:latest'
        build: ./dockerfiles/custom-httpd-container/
        restart: always
        ports:
            - '35504:80'
        volumes:
            - 'prod-client-build:/usr/local/apache2/htdocs/'


    prodServer:
        container_name: prod-server
        image: 'tomcat:9.0'
        restart: always
        ports:
            - '35503:8080'
        depends_on:
            - prodMySQL
        environment:
            - JAVA_OPTS=-Dspring.profiles.active=prod
        volumes:
            - 'prod-server-build:/usr/local/tomcat/webapps/'



volumes:
    gitlab-runner-config:
        external: false

    test-mysql-data:
        external: false
    prod-mysql-data:
        external: false

    test-client-build:
        external: false
    test-server-build:
        external: false
    prod-client-build:
        external: false
    prod-server-build:
        external: false
