version: '3.3'
services:
    
    mysql:
        image: 'mysql:8.0.22'
        container_name: capacitor-mysql
        restart: always
        network_mode: host
        environment:
                MYSQL_DATABASE: capacitor_test
        env_file:
                - mysql-variables.env

    phpmyadmin:
        image: 'phpmyadmin:5.0.2-apache'
        container_name: phpmyadmin
        environment:
            # The address 172.17.0.1 is localhost for docker
            - PMA_HOST=172.17.0.1
            - PMA_PORT=3306
        restart: always
        ports:
            - '8081:80'
            - '8082:443'

    capacitor-gitlab-runner:
        container_name: gitlab-runner
        image: 'capacitor-gitlab-runner:latest'
        build: ./dockerfiles/custom-gitlab-runner-container/
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'gitlab-runner-config:/etc/gitlab-runner'
        network_mode: host


volumes:
    gitlab-runner-config:
        external: false


