version: '3.3'
services:
    
    mysql:
        image: 'mysql:8.0.22'
        container_name: capacitor-mysql
        restart: always
        network_mode: host
        environment:
                MYSQL_DATABASE: capacitor_test
        env_file:
                - mysql-variables.env

    phpmyadmin:
        container_name: phpmyadmin
        image: 'capacitor-phpmyadmin:latest'
        build: ./dockerfiles/custom-phpmyadmin-container/
        environment:
            # The address 172.17.0.1 is localhost for docker
            - PMA_HOST=172.17.0.1
            - PMA_PORT=3306
        restart: always
        ports:
            - '8081:443'
        volumes:
            - '/etc/apache2/ssl:/certs:ro'
        hostname: 'capacitor-archive.com'

    capacitor-gitlab-runner:
        container_name: gitlab-runner
        image: 'capacitor-gitlab-runner:latest'
        build: ./dockerfiles/custom-gitlab-runner-container/
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'gitlab-runner-config:/etc/gitlab-runner'
            - 'test-client-build:/home/gitlab-runner/test-client/'
            - 'test-server-build:/home/gitlab-runner/test-server/'
        network_mode: host

    testClient:
        container_name: test-client
        image: 'httpd:alpine'
        restart: always
        ports:
            - '35504:80'
        volumes:
            - 'test-client-build:/usr/local/apache2/htdocs/'


    testServer:
        container_name: test-server
        image: 'tomcat:9.0-slim'
        restart: always
        ports:
            - '35503:8080'
            #- '3306:3306'  # Run server with in-memory database for now
        volumes:
            - 'test-server-build:/usr/local/tomcat/webapps/'


volumes:
    gitlab-runner-config:
        external: false
    test-client-build:
        external: false
    test-server-build:
        external: false


