
export const historicCountryList =  [
  'Albania',
  'Algeria',
  'Angola',
  'Argentina',
  'Austria',
  'Belgium',
  'Czechoslovakia',
  'Denmark',
  'France',
  'Germany',
  'Great Britain (UK)',
  'Greece',
  'Guernsey',
  'Hungary',
  'Italy',
  'Latvia (Latvia, Riga)',
  'Morocco',
  'Mozambique',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Panama',
  'China',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russian Federation',
  'Singapore',
  'Slovak Republic',
  'South Africa',
  'South Korea',
  'Soviet Union',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan (Republic of China)',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Ukraine',
  'United States of America (USA)',
  'Uruguay',
  'Worldwide',
  'Yugoslavia',
  'Zimbabwe'
];
