FROM linuxserver/ddclient

#COPY ./ddclient.conf /config/ddclient.conf
#COPY ./ddclient.conf /etc/ddclient/ddclient.conf

#RUN sed -i -e "s/DYNAMIC_DNS_PASSWORD/$DYNAMIC_DNS_PASSWORD/g" /etc/ddclient/ddclient.conf

